config/routes.rb
Rails.application.routes.draw do
  
  
  get 'uploadfile/index'
  get 'uploadfile/new'
  get 'uploadfile/create'
  get 'uploadfile/destroy'
  resources :taskdetails
  resources :projects
  resources :organizations
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get 'pages/crete'
  get 'pages/edit'
  get 'pages/update'
  get 'pages/destroy'
  get 'pages/new'
  get  'pages/about'


  # get 'displayqr/show'
  # get  'diplayqr/update'
  # get 'diplayqr/refresh'

  # get 'checkga/show'

  # get 'checkga/update'

  devise_for :users, :controllers => {:confirmations => 'confirmations', :registrations => 'registrations'} 

   def devise_displayqr(mapping, controllers)
      resource :displayqr, :only => [:show, :update], :path => mapping.path_names[:displayqr], :controller => controllers[:displayqr] do
        post :refresh, :path => mapping.path_names[:refresh], :as => :refresh
      end
      resource :checkga, :only => [:show, :update], :path => mapping.path_names[:checkga], :controller => controllers[:checkga]
    end

   
resources :checkga do
    collection do
      put :show
     end
  end

  resources :displayqr do
    collection do
      post :show
     end
  end

# resources :users do
#     member do
#       get :displayqr_update, to: 'users/displayqr#update'
#       post :devisepq_show, to: 'users/displayqr#show'
#     end
#   end
  # devise_for :users,controllers: { confirmations: 'confirmations', registrations: 'registrations'} 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/taskdetail.rb
class Taskdetail < ApplicationRecord
belongs_to :project
# ,required: false
end

app/controllers/taskdetails_controller.rb
class TaskdetailsController < InheritedResources::Base
before_action :set_taskdetail, only: [:show, :edit, :update]
before_action :authenticate_user!
# before_filter :authenticate_user!
def index
 @taskdetails = Taskdetail.all
 

end

def show


end


def new
@taskdetail = Taskdetail.new
end



def edit


end


def create
	@taskdetails = Taskdetail.new(taskdetail_params)
   @taskdetails.project_id = params[:project][:prjname]
    respond_to do |format|
      if @taskdetails.save
        format.html { redirect_to @taskdetails, notice: 'Succssfully Created.' }
        format.json { render :show, status: :Success, location: @taskdetails }
      else
        format.html { render :new }
        
      end
    end
end


def update
@taskdetail = Taskdetail.find(params[:id])
@taskdetails.project_id = params[:project][:prjname]

respond_to do |format|
      if @taskdetail.update(taskdetail_params)
        format.html { redirect_to @taskdetail, notice: 'Succssfully Updated task data' }
        format.json { render :show, status: :Success, location: @taskdetail }
      else
        format.html { render :edit }
        format.json { render json: @taskdetail.errors, status: :failed }
      end
    end

end

def destroy


end





  private

  def set_taskdetail
  @taskdetail = Taskdetail.find(params[:id])
  end

    def taskdetail_params
      params.require(:taskdetail).permit(:name, :days,:status,:project_id)
    end
end

app/helpers/taskdetails_helper.rb
module TaskdetailsHelper
end

app/views/taskdetails/_form.html.erb
<div class="authform">
<%= form_with(model: taskdetail, local: true) do |form| %>
  <% if taskdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taskdetail.errors.count, "error") %> prohibited this taskdetail from being saved:</h2>

      <ul>
      <% taskdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name ,class: "form-control"%>
  </div>

 <!--  <div class="form-group">
    <%= form.label :project_id %>
    <%= form.number_field :project_id ,class: "form-control" %>
  </div> -->


 <div class="form-group">
    <%= form.label :days %>
    <%= form.number_field :days ,class: "form-control"%>
  </div>
   <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status ,class: "form-control"%>
  </div>

   <div class="form-group">
    <%= form.label :project_list %>
   <%= collection_select( :project, :prjname ,Project.all, :id, :prjname, { :multiple => false} ) %>
  </div>

  
  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/taskdetails/edit.html.erb
<h1>Editing Taskdetail</h1>

<%= render 'form', taskdetail: @taskdetail %>

<%= link_to 'Show', @taskdetail %> |
<%= link_to 'Back', taskdetails_path %>

app/views/taskdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taskdetails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @taskdetails.each do |taskdetail| %>
      <tr>
        <td><%= taskdetail.name %></td>
        <td><%= taskdetail.project_id %></td>
        <td><%= link_to 'Show', taskdetail %></td>
        <td><%= link_to 'Edit', edit_taskdetail_path(taskdetail) %></td>
        <td><%= link_to 'Destroy', taskdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Detail', new_taskdetail_path %>

app/views/taskdetails/new.html.erb
<!-- <div class="form-group">
 	 <%= button_to "Back", taskdetails_path , class: "btn btn-primary" %>
 	</div> -->
<h1 style="text-align: center;">New Task Details</h1>
<%= render 'form', taskdetail: @taskdetail %>

app/views/taskdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @taskdetail.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @taskdetail.project_id %>
</p>

<%= link_to 'Edit', edit_taskdetail_path(@taskdetail) %> |
<%= link_to 'Back', taskdetails_path %>